name: workflow_dispatch-triggger

on:
    workflow_dispatch:
        inputs:
            REPO_NAME:
                type: string
                required: true

jobs:
    sample_job:
        runs-on: ubuntu-latest
        steps:
        - name: print input_var
          run: echo ${{inputs.REPO_NAME}}